version: "3.2"

services:
  backend:
    image: node:10
    ports:
      - 3000:3000
    volumes:
      - ./backend:/server
    command: sh -c 'cd /server && yarn && yarn start:dev'
    # logging:
    #   driver: none
  db:
    ports:
      - 3306:3306
    # volumes:
    # - ./volumes/database:/var/lib/mysql
    # logging:
    #   driver: none
  grafana:
    ports: 
      - 7654:3000
  nginx:
    image: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./config/sites-enabled/server.conf:/etc/nginx/sites-enabled/server.conf
    depends_on:
      - backend
